pub mod cadence;
pub mod config;
pub mod detection;
pub mod efficiency;
pub mod instrument;
pub mod lightcurve;
pub mod pipeline;
pub mod population;
pub mod spatial;
pub mod survey;
pub mod types;

pub use config::SimulationConfig;
pub use detection::{DetectionCriteria, DetectionResult};
pub use instrument::InstrumentConfig;
pub use lightcurve::{LightcurveEvaluation, LightcurveModel};
pub use pipeline::{SimulationPipeline, SimulationResult};
pub use population::{PopulationGenerator, TransientPopulation};
pub use survey::{SurveyLoader, SurveyObservation, SurveyStore};
pub use types::{Band, Cosmology, SkyCoord, TransientInstance, TransientType};
